"""Company_and_Project_Model

Revision ID: 2e1f729f1813
Revises: 
Create Date: 2025-08-13 13:21:57.808091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by alembic.
revision: str = '2e1f729f1813'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by alembic - please adjust! ###
    op.alter_column('Company', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'bio_min',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'bio_max',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'keywords',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'geo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'coordinates',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'use_technology',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'contact_number_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'contact_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'contact_site',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'contact_tg',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'contact_vk',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'official_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Company', 'founding_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by alembic - please adjust! ###
    op.alter_column('Company', 'founding_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'official_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'contact_vk',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'contact_tg',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'contact_site',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'contact_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'contact_number_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'use_technology',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'coordinates',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'geo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'keywords',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'bio_max',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'bio_min',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Company', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end alembic commands ###
